In [18]:
#Why and how to code ordinary cathegorical data by using python with sklearn and panda
#Context is to work with data from a survey
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler

#ordinal codificator
from sklearn.preprocessing import OrdinalEncoder

#codificator OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

cathegorical_service = ["Muy insatisfecho", "Insatisfecho", "Neutral", "Satisfecho", "Muy satisfecho"]
cahtegorical_quality = ["Mala", "Buena", "Muy buena", "Excelente"]

survey = {"service" : ["Muy insatisfecho", "Insatisfecho",
                       "Neutral", "Satisfecho", "Muy satisfecho",
                       "Muy satisfecho"],
          "food": ["Mala", "Buena", "Muy buena",
                   "Excelente", "Mala", "Buena"]
          }

#sporadic customer  frecuent customer
client_type = [0,0,1,1,0,1]

pd.DataFrame(survey)




service       food
0  Muy insatisfecho       Mala
1      Insatisfecho      Buena
2           Neutral  Muy buena
3        Satisfecho  Excelente
4    Muy satisfecho       Mala
5    Muy satisfecho      Buena

In [8]:
data_ord= pd.DataFrame(survey)
codificator = OrdinalEncoder (categories = [cathegorical_service, cahtegorical_quality])

data_ord = pd.DataFrame(codificator.fit_transform(data_ord),
                        columns=["service", "food"])
print(data_ord)
print(codificator.categories_)

   service  food
0      0.0   0.0
1      1.0   1.0
2      2.0   2.0
3      3.0   3.0
4      4.0   0.0
5      4.0   1.0
[array(['Muy insatisfecho', 'Insatisfecho', 'Neutral', 'Satisfecho',
       'Muy satisfecho'], dtype=object), array(['Mala', 'Buena', 'Muy buena', 'Excelente'], dtype=object)]


In [19]:
data_one = pd.DataFrame(survey)
codificator = OneHotEncoder()

print(codificator.fit_transform(data_one).toarray())

#union between two dataframes to link survey data to clasification dataframe
#print(np.concatenate(codificator.categories_))

data_one = pd.DataFrame(codificator.fit_transform(data_one).toarray(),
                        columns=np.concatenate(codificator.categories_))

data_one

[[0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0.]]


Insatisfecho  Muy insatisfecho  Muy satisfecho  Neutral  Satisfecho  Buena  \
0           0.0               1.0             0.0      0.0         0.0    0.0   
1           1.0               0.0             0.0      0.0         0.0    1.0   
2           0.0               0.0             0.0      1.0         0.0    0.0   
3           0.0               0.0             0.0      0.0         1.0    0.0   
4           0.0               0.0             1.0      0.0         0.0    0.0   
5           0.0               0.0             1.0      0.0         0.0    1.0   

   Excelente  Mala  Muy buena  
0        0.0   1.0        0.0  
1        0.0   0.0        0.0  
2        0.0   0.0        1.0  
3        1.0   0.0        0.0  
4        0.0   1.0        0.0  
5        0.0   0.0        0.0

In [20]:
#logistic regresuin clasifier
print("\n*** sacalung data to ordinal codification")
scaler = MinMaxScaler()

print(data_ord)
data_ord = scaler.fit_transform(data_ord)
print(data_ord)

print("\n*** Clasification with coded data into Ordinal Encoder")
model = LogisticRegression().fit(data_ord, client_type)

print("Preduction", model.predict(data_ord))
print("Correct classes", client_type)
print(model.predict_proba(data_ord))

print("\n*** clasification by coded data with OneHotEncoder")
model = LogisticRegression().fit(data_one, client_type)

print("Preduction", model.predict(data_ord))
print("Correct classes", client_type)
print(model.predict_proba(data_ord))



*** sacalung data to ordinal codification
   service  food
0      0.0   0.0
1      1.0   1.0
2      2.0   2.0
3      3.0   3.0
4      4.0   0.0
5      4.0   1.0
[[0.         0.        ]
 [0.25       0.33333333]
 [0.5        0.66666667]
 [0.75       1.        ]
 [1.         0.        ]
 [1.         0.33333333]]

*** Clasification with coded data into Ordinal Encoder
Preduction [0 0 1 1 0 1]
Correct classes [0, 0, 1, 1, 0, 1]
[[0.6223418  0.3776582 ]
 [0.54247948 0.45752052]
 [0.46037256 0.53962744]
 [0.38036146 0.61963854]
 [0.52598074 0.47401926]
 [0.4684709  0.5315291 ]]

*** clasification by coded data with OneHotEncoder


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


ValueError: X has 2 features, but LogisticRegression is expecting 9 features as input.